---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
  -
      bundler_args:
      dist: trusty
      env: PLATFORMS=debian_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_debian]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=debian_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_debian]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=ubuntu_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_ubuntu]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=ubuntu_puppet6
      rvm: 2.5.3
      before_script:
      - time bundle exec rake 'litmus:provision_list[waffle_ubuntu]'
      - time bundle exec rake 'litmus:install_agent[puppet6]'
      - time bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=centos6_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_centos6]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=centos6_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_centos6]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=scientificlinux6_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_scientificlinux6]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=scientificlinux6_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_scientificlinux6]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el7_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el7]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el7_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el7]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false

